---
# Step 1: Install the Web Terminal operator via OLM
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    demo.redhat.com/application: "web-terminal"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: {{ .Values.operator.name }}
  source: {{ .Values.operator.source }}
  sourceNamespace: {{ .Values.operator.sourceNamespace }}
