---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    demo.redhat.com/application: "{{ .Values.app.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  greeting: {{ .Values.config.greeting | quote }}