---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    demo.redhat.com/application: "{{ .Values.app.name }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: {{ .Values.application.service.type }}
  ports:
  - port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}