---
namespace: agnosticd
name: core
version: 1.0.0
readme: README.md
authors:
  - Field Content Team
description: Local copy of agnosticd core plugins for field content demos
license:
  - GPL-3.0-or-later
dependencies: {}
