apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: field-content-demo
  labels:
    app: field-content-demo
    demo.redhat.com/application: "field-content-demo"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  greeting: "Hello from Kustomize Field Content!"
  demo_type: "kustomize"