---
- name: Validate field content repository URL is provided
  ansible.builtin.fail:
    msg: "ocp4_workload_field_content_gitops_repo_url is required but not provided"
  when: ocp4_workload_field_content_gitops_repo_url == "" or ocp4_workload_field_content_gitops_repo_url is not defined

- name: Set _ocp4_workload_field_content_deployer_values
  ansible.builtin.set_fact:
    _ocp4_workload_field_content_deployer_values:
      deployer:
        domain: "{{ openshift_cluster_ingress_domain }}"
        apiUrl: "{{ openshift_api_url }}"
      fieldContent:
        deploymentType: "{{ ocp4_workload_field_content_deployment_type }}"

- name: Debug _ocp4_workload_field_content_deployer_values
  ansible.builtin.debug:
    msg: "{{ _ocp4_workload_field_content_deployer_values | to_yaml }}"

- name: Create field content ArgoCD application
  kubernetes.core.k8s:
    state: present
    template: application.yaml.j2

- name: Wait until field content ArgoCD application is healthy and synced
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: field-content
    namespace: "{{ ocp4_workload_field_content_namespace }}"
  register: argocd_field_content
  retries: "{{ ocp4_workload_field_content_health_retries }}"
  delay: 10
  until:
  - argocd_field_content is defined
  - argocd_field_content.resources is defined
  - argocd_field_content.resources | length > 0
  - argocd_field_content.resources[0].status is defined
  - argocd_field_content.resources[0].status.health.status == "Healthy"
  - argocd_field_content.resources[0].status.sync.status == "Synced"
  ignore_errors: "{{ ocp4_workload_field_content_health_ignore | bool }}"

- name: Pause for a minute while the field content app deploys
  ansible.builtin.pause:
    seconds: 60

- name: Validate all applications with our label in any namespace are healthy and synced
  when: ocp4_workload_field_content_application_wait | bool
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    label_selectors:
    - "demo.redhat.com/application"
  register: _all_apps
  delay: 10
  retries: "{{ ocp4_workload_field_content_application_health_retries }}"
  until:
  - _all_apps is defined
  - _all_apps.resources is defined
  # json_query: length of list of resources found == length of list of those with good status
  - _all_apps.resources | json_query('length([?status.health.status==`Healthy` || status.health.status==`Suspended`]) == length(@)')
  - _all_apps.resources | json_query('length([?status.sync.status==`Synced`]) == length(@)')

#######
####### Begin processing GitOps output
#######

- name: Retrieve ConfigMaps with the demo.redhat.com/userinfo label
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    label_selectors:
    - "demo.redhat.com/userinfo"
  register: cm_userinfo

- name: If ConfigMaps were found, process them
  when:
  - cm_userinfo.resources is defined
  - cm_userinfo.resources | length | int > 0
  block:
  - name: Add to agnosticd_user_info all data from ConfigMaps except configmap.data.users_json data
    agnosticd.core.agnosticd_user_info:
      data: >-
        {{ item | dict2items | selectattr('key', 'ne', 'users_json') | items2dict }}
    loop: "{{ cm_userinfo.resources | map(attribute='data') }}"

  - name: Prepare data_user_json to add to agnosticd_user_info
    ansible.builtin.debug:
      msg: "Prepare data_user_json to add to agnosticd_user_info"

  - name: Merge list of all users_json data from all ConfigMaps that have data.users_json
    ansible.builtin.set_fact:
      data_users_json: "{{ data_users_json | default([]) | combine(item.data.users_json | from_json, recursive=True) }}"
    loop: "{{ cm_userinfo.resources }}"
    when: item.data.users_json is defined

  - name: Handle data_users_json data
    when: data_users_json is defined
    block:
    - name: Debug merged data_users_json data
      ansible.builtin.debug:
        msg: "{{ data_users_json }}"

    - name: Add to agnosticd_user_info all configmap.data.users_json ConfigMap data
      agnosticd.core.agnosticd_user_info:
        user: "{{ item.key }}"
        data:
          "{{ item.value }}"
      loop: "{{ data_users_json.users | dict2items }}"
      when: data_users_json is defined

- name: Debug user_data
  ansible.builtin.debug:
    msg: "{{ lookup('agnosticd_user_data', '*') }}"
